version: '3'
services:
  bot:
    build: ./bot
    depends_on:
      - db
    volumes:
      - ./bot:/app
    networks:
      - my_network

  db:
    build: ./db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
    driver: bridge
